#!/usr/bin/env python
#encoding: utf-8

#
# Copyright (C) 2015 Focalcrest, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

def options(opt):
	opt.load('compiler_cxx')

def configure(ctx):
	print('configure graphics')
	ctx.load('compiler_cxx')

def build(bld):
	print('compile graphics')
	bld.stlib(target='xsgraphics', source=bld.path.ant_glob('**/src/*.cpp'), includes=bld.env.INC_PATH + ' include /usr/include /usr/include/gtk-2.0 /usr/include/atk-1.0 /usr/include/cairo /usr/include/gdk-pixbuf-2.0 /usr/include/pango-1.0 /usr/include/gio-unix-2.0 /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include /usr/include/pixman-1 /usr/include/freetype2 /usr/include/libpng12 /usr/lib/x86_64-linux-gnu/gtk-2.0/include /usr/include/x86_64-linux-gnu /usr/lib/gcc/x86_64-linux-gnu/4.6.3/include')
