#!/usr/bin/env python
#encoding: utf-8

def configure(ctx):
	print('configure pal linux')
	ctx.load('compiler_cxx')

def build(bld):
	print('compile pal linux')
	bld.stlib(target='pallinux', source=bld.path.ant_glob('**/src/*.cpp **/src/*.c'), includes=bld.env.INC_PATH + ' include /usr/include /usr/include/gtk-2.0 /usr/include/atk-1.0 /usr/include/cairo /usr/include/gdk-pixbuf-2.0 /usr/include/pango-1.0 /usr/include/gio-unix-2.0 /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include /usr/include/pixman-1 /usr/include/freetype2 /usr/include/libpng12 /usr/lib/x86_64-linux-gnu/gtk-2.0/include /usr/include/x86_64-linux-gnu /usr/lib/gcc/x86_64-linux-gnu/4.6.3/include')
	#bld.stlib(target='pallinux', source=bld.path.ant_glob('**/src/*.cpp **/src/*.c'), includes=bld.env.INC_PATH + ' include /usr/include /usr/include/gtk-2.0 /usr/include/atk-1.0 /usr/include/cairo /usr/include/gdk-pixbuf-2.0 /usr/include/pango-1.0 /usr/include/gio-unix-2.0 /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include /usr/include/pixman-1 /usr/include/freetype2 /usr/include/libpng12 /usr/lib/x86_64-linux-gnu/gtk-2.0/include /usr/include/x86_64-linux-gnu /usr/lib/gcc/x86_64-linux-gnu/4.6.3/include', uselib='mob-objects GCC',  packages='gtk+-2.0')
