#!/usr/bin/env python
#encoding: utf-8

def options(opt):
	opt.load('compiler_cxx')

def configure(ctx):
	ctx.env.TEST = 'Hello'

def build(bld):
	pass

def test(ctx):
	#print(ctx.env.TEST)	
	print('Linux')
