#!/usr/bin/env python
#encoding: utf-8

#
# Copyright (C) 2015 Focalcrest, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

def configure(ctx):
	print('configure paldarwin')
	ctx.load('compiler_c')
	ctx.load('compiler_cxx')

def build(bld):
	print('compile paldarwin')
	#bld.env.LIBS += ''
	bld.stlib(features='c cxx', cflags='-fobjc-arc', target='paldarwin', source=bld.path.ant_glob('**/*.cpp **/*.c **/*.m'), includes=bld.env.INC_PATH + ' include')

from waflib import TaskGen
@TaskGen.extension('.m')
def m_hook(self, node):
	"""Alias .m files to be compiled the same as .c files, gcc will do the right thing."""
	return self.create_compiled_task('c', node)
