#!/usr/bin/env python
#encoding: utf-8

import os
from waflib import Utils

def dirs(ctx):
	path = ctx.path.abspath()
	DIRS = [t for t in Utils.listdir(path) if os.path.isfile(os.path.join(path, t, 'wscript'))]
	return DIRS

def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	for d in dirs(conf):
		conf.recurse(d)

def build(bld):
	for d in dirs(bld):
		bld.recurse(d)
