#!/usr/bin/env python
#encoding: utf-8

#
# Copyright (C) 2015 Focalcrest, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

def configure(ctx):
	print('configure palwin32')
	ctx.load('compiler_cxx')
	ctx.check_libs_msvc('GDIPLUS GDI32 WS2_32 OLE32 USER32 KERNEL32')

def build(bld):
	print('compile palwin32')
	bld.env.LIBS += 'GDIPLUS GDI32 WS2_32 OLE32 USER32 KERNEL32'
	bld.stlib(target='palwin32', source=bld.path.ant_glob('**/src/*.cpp **/src/*.c'), includes=bld.env.INC_PATH + ' include', defines=['UNICODE', '_UNICODE', 'WIN32'])
