#!/usr/bin/env python
#encoding: utf-8

import os

def configure(ctx):
	print('configure core')
	ctx.load('compiler_cxx')

def build(bld):
	print('compile core')
	bld.env.CLASSPATH = os.path.join(bld.env.TOP_DIR, 'tools', 'xslt', '*')
	bld.env.XSL_PATH = os.path.join(bld.env.TOP_DIR, 'tools', 'xslt', 'classid.xsl')
	bld(rule='java -classpath "${CLASSPATH}" org.apache.xalan.xslt.Process -out ${TGT} -in ${SRC} -xsl ${XSL_PATH} -param use.extensions 1', source=bld.path.make_node('classdef.xml'), target=bld.path.make_node('include/xs/coreclassid.h'))
	bld.stlib(target='xscore', source=bld.path.ant_glob('**/src/*.cpp **/gen/*.cpp'), includes=bld.env.INC_PATH + ' include ../graphics/include /usr/include /usr/include/gtk-2.0 /usr/include/atk-1.0 /usr/include/cairo /usr/include/gdk-pixbuf-2.0 /usr/include/pango-1.0 /usr/include/gio-unix-2.0 /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include /usr/include/pixman-1 /usr/include/freetype2 /usr/include/libpng12 /usr/lib/x86_64-linux-gnu/gtk-2.0/include /usr/include/x86_64-linux-gnu /usr/lib/gcc/x86_64-linux-gnu/4.6.3/include',  use='xsgraphics')
