#!/usr/bin/env python
#encoding: utf-8

def options(opt):
	opt.load('compiler_cxx')

def configure(ctx):
	print('configure xsdemo')
	ctx.load('compiler_cxx')

def build(bld):
	print('compile xsdemo')
	bld.program(target='xsdemo', source=bld.path.ant_glob('**/src/*.cpp'), includes=bld.env.INC_PATH, use='xscore palwin32', lib='GDIPLUS GDI32 WS2_32 OLE32 USER32 KERNEL32', subsystem='windows')


