#!/usr/bin/env python
#encoding: utf-8

def options(opt):
	opt.load('compiler_cxx')

def configure(ctx):
	print('configure xsdemo')
	ctx.load('compiler_cxx')

def build(bld):
	print('compile xsdemo')
	bld.program(target='xsdemo', source=bld.path.ant_glob('**/src/*.cpp'), includes=bld.env.INC_PATH, use='xsgraphics xscore xsjavascript xsduktape ' + bld.env.PAL_LIB, lib=bld.env.LIBS, subsystem='windows')
